### ISSUE TITLE
1.5.6 -> 1.5.7 API break

### ISSUE THREAD

**Issue by stavling** [gunyarakun/timezone_finder#1]
Hi, really like the gem, however I do feel I need to criticise the update. It doesn't really warrant an issue, perhaps, so feel free to close it whenever.

It's fine to update the API, however, then you _have_ to up the MINOR or MAJOR version. The PATCH is only meant for backwards-compatible changes. I had my Gemfile set up with 1.5.x so I would get the patches. But the automatic update broke it :/

Thanks :)

**Comment by gunyarakun** [comment]
I completely agree with you, @stavling.

If we change the API, we should change MINOR or MAJOR version. So, could you tell *the original author* to do so instead of me?

I keep the version number of this Ruby module is as the same as the original Python's.
In 1.5.7, the API broke occurred in original Python module which forces arguments to have names.
I considered I should follow the version rule or break the compatibility. The original Python module broke the API compatibility even in Python, so I translated as it was.

I have a version line '~> 1.5.6' in my Gemfile and this update broke my project. It irritated me.

So I wrote the line in README.md.

```
NOTE: version 1.5.7 is incompatible with version 1.5.6 because the arguments were changed into named arguments following the original Python version's change.
```

Or do you have any alternative?

**Comment by jannikmi** [comment]
I am sorry for this. 
Read the changelog to check if its really worth updating for you:
https://github.com/MrMinimal64/timezonefinder/blob/master/CHANGELOG.rst

We decided it was a necessary step to eradicate lng lat mix-up confusions.
Shouldn't be a huge deal for you to change your code using keyword arguments however.
Greetings

**Comment by stavling** [comment]
@gunyarakun I'm not sure what would be the right way. Honestly, I've never maintained a public repo so this is new territory for me. I understand that there is value in having the version number reflect the one in the original module. But in this case, where the original broke the API, I would say that it is not worth it.  After all, bundler doesn't read the README ;)

@MrMinimal64 It does not matter how big of a deal it is. I agree that it is better with keyword arguments. However, if the API changes, up the MAJOR. It's common to have your package manager automatically update PATCHES. But now I have locked down the version in my project to prevent breakages.

**Comment by jannikmi** [comment]
You are completely right. Should have done that. Hopefully the next big update is out soon, then we'll up the major.
